version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: 'npm'
    directory: '/frontend/marguerite-protfolio-angular-front'
    schedule:
      interval: 'daily'

  - package-ecosystem: "gradle"
    directory: "/backend/api-marguerite-l-portfolio"
    schedule:
      interval: "daily"
