apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: 'marguerite-lanson'
  name: marguerite-lanson-api-ingress
  annotations:
    spec.ingressClassName: traefik
spec:
  tls:
    - secretName: marguerite-lanson-api-certificate-tls
  rules:
    - host: api.marguerite-lanson.com
      http:
        paths:

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 80

          - path: /projects
            pathType: Prefix
            backend:
              service:
                name: projcets
                port:
                  number: 80
